# Generated by Django 3.2.2 on 2021-06-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_album', models.CharField(max_length=55, verbose_name='Заголовок альбома')),
                ('description_album', models.TextField(verbose_name='Описание альбома')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст новсти')),
                ('title_news', models.CharField(max_length=55, verbose_name='Заголовок новости')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публткации')),
                ('photo', models.ImageField(blank=True, upload_to='photos/', verbose_name='Картинка')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имена авторов')),
                ('name_trak', models.CharField(max_length=20, verbose_name='Название трека')),
                ('audio', models.FileField(blank=True, upload_to='audio/', verbose_name='аудио')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
        migrations.CreateModel(
            name='Trak_in_album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имена авторов')),
                ('name_trak1', models.CharField(max_length=20, verbose_name='Название трека')),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxxxy2.album')),
            ],
            options={
                'verbose_name': 'Трек в альбоме',
                'verbose_name_plural': 'Треки в альбоме',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(max_length=350, verbose_name='Текст коментария')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публткации коментария')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxxxy2.news')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
