# Generated by Django 4.0 on 2022-03-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oxxxy2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trak_in_album',
            name='album',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='description_album',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='title_album',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_news',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='trak',
            old_name='name_trak',
            new_name='name',
        ),
        migrations.AddField(
            model_name='trak',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trak_set', to='oxxxy2.album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=999, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=999, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='trak',
            name='slug',
            field=models.SlugField(max_length=999, unique=True, verbose_name='URL'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Trak_in_album',
        ),
    ]
