# Generated by Django 4.0 on 2022-03-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxxxy2', '0002_remove_trak_in_album_album_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trak',
            name='author',
        ),
        migrations.AddField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_album/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публткации'),
        ),
        migrations.AddField(
            model_name='trak',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_news/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_news/', verbose_name='Картинка'),
        ),
    ]
